environments:
  Production:
    pipelines:
      - GoCDQueueMonitor-BuildDeploy
pipelines:
  GoCDQueueMonitor-BuildDeploy:
    group: EvolucaoInfra
    materials:
      git-repo:
        git: git@github.com:stone-payments/gocd-queue-monitor.git
        branch: master
    stages:
      - UnitTests:
          clean_workspace: true
          jobs:
            UnitTest:
              elastic_profile_id: docker.python3
              tasks:
               - exec:
                   command: pip3
                   arguments:
                    - install
                    - -r
                    - requirements.txt
               - exec:
                   command: python3
                   arguments:
                   - -m
                   - pytest
      - Zip:
          jobs:
            Zip:
              elastic_profile_id: docker.python3
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                     - -c
                     - zip -r dist.zip .
      - SetTsuruEnvs:
          jobs:
            SetTsuruEnvs:
              elastic_profile_id: docker.python3
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                    - -c
                    -  python /go/tsuru-pydeploy/tsuru_set_env.py -a $APP_NAME -u $TSURU_USER -p $TSURU_PASSWORD -s $TSURU_HOST
      - DeployZipToTsuru:
          jobs:
            DeployZipToTsuru:
              elastic_profile_id: docker.python3
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                    - -c
                    - python /go/tsuru-pydeploy/tsuru_app_deploy.py -a $APP_NAME -i ./dist.zip -u $TSURU_USER -p $TSURU_PASSWORD -s $TSURU_HOST
